C *************************************************************************
      SUBROUTINE DELETEFILE(FILENAME,STATUS)

C  A SIMPLE LITTLE ROUTINE TO DELETE A FITS FILE

      INTEGER STATUS,UNIT,BLOCKSIZE
      CHARACTER*(*) FILENAME

C  SIMPLY RETURN IF STATUS IS GREATER THAN ZERO
      IF (STATUS .GT. 0)RETURN

C  GET AN UNUSED LOGICAL UNIT NUMBER TO USE TO OPEN THE FITS FILE
      CALL FTGIOU(UNIT,STATUS)

C  TRY TO OPEN THE FILE, TO SEE IF IT EXISTS
      CALL FTOPEN(UNIT,FILENAME,1,BLOCKSIZE,STATUS)

      IF (STATUS .EQ. 0)THEN
C         FILE WAS OPENED;  SO NOW DELETE IT 
          CALL FTDELT(UNIT,STATUS)
      ELSE IF (STATUS .EQ. 103)THEN
C         FILE DOESN'T EXIST, SO JUST RESET STATUS TO ZERO AND CLEAR ERRORS
          STATUS=0
          CALL FTCMSG
      ELSE
C         THERE WAS SOME OTHER ERROR OPENING THE FILE; DELETE THE FILE ANYWAY
          STATUS=0
          CALL FTCMSG
          CALL FTDELT(UNIT,STATUS)
      END IF

C  FREE THE UNIT NUMBER FOR LATER REUSE
      CALL FTFIOU(UNIT, STATUS)
      END
