include MakefileF77.in
LIBFITSIO = fitsio503/libfitsio.a
TARGET1 = cookbook
TARGETS = $(TARGET1)
OUTFILES = *TESTFILEZ.FITS*
LIBS = $(LIBFITSIO)

.PHONY: clean  all

all: $(TARGETS)
	echo "done all targets"

$(LIBFITSIO):
	cd fitsio503; \
	./configure; \
	make all

$(TARGET1): $(OBJ) $(LIBFITSIO)
	$(FC) -o $@ $^ $(LDFLAGS) $(LIBS)


clean:
	rm -f $(OBJ) $(OUTFILES)

distclean: clean
	rm -f $(TARGETS) $(LIBFITSIO)


